import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json({
    status: "approval_required",
    message: "Tracking URLs and learning decisions are generated by the Python service.",
    endpoints: {
      tracking: "app.services.tracked_offer_url",
      learning: "app.services.learning_decision",
    },
  });
}
